version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cibuilds/hugo:latest
        user: root

    working_directory: /hugo
    steps:
      - run:
          name: Update enviroment
          command: apk update && apk add git
      - checkout
      - run:
          name: Building blog pages
          command: hugo -v
      - add_ssh_keys:
          fingerprints:
            - "d2:e3:99:d9:b4:3a:a2:ea:b8:1c:46:0c:37:f8:c6:a0"
      - deploy:
          name: Deploy to GitHub Pages
          command: ./.circleci/deploy.sh
